/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_jni_NativeLib */

#ifndef _Included_com_zilliz_spark_connector_jni_NativeLib
#define _Included_com_zilliz_spark_connector_jni_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zilliz_spark_connector_jni_NativeLib$
 * Method:    getGreeting
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zilliz_spark_connector_jni_NativeLib_00024_getGreeting
  (JNIEnv *, jobject);

/*
 * Class:     com_zilliz_spark_connector_jni_NativeLib$
 * Method:    processArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_zilliz_spark_connector_jni_NativeLib_00024_processArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_zilliz_spark_connector_jni_NativeLib$
 * Method:    calculateSum
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_com_zilliz_spark_connector_jni_NativeLib_00024_calculateSum
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     com_zilliz_spark_connector_jni_NativeLib$
 * Method:    processString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zilliz_spark_connector_jni_NativeLib_00024_processString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
